=head1 Dist::Zilla::Role::Stash::Plugins

This is a L<Dist::Zilla::Role> for a L<Stash|Dist::Zilla::Role::Stash>
which uses L<Dist::Zilla::Role::DynamicConfig>
to store configuration arguments for other plugins.

See POD in the modules for more information
or L<Dist::Zilla::Stash::PodWeaver> which actually uses this role.

=cut
