=head1 Dist::Zilla::Role::Stash::Plugins

This is a L<Dist::Zilla::Role> for a L<Stash|Dist::Zilla::Role::Stash>
which uses L<Dist::Zilla::Role::DynamicConfig>
to store configuration arguments for other plugins.

See POD in the modules for more information
or L<Dist::Zilla::Stash::PodWeaver> which actually uses this role.

=head1 HISTORY

This repository was forked form the original
L<Dist::Zilla::Stash::PodWeaver> repository
after some of its components were generalized.

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2010 by Randy Stauner.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
